# Generated by Django 4.1 on 2022-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
