# Generated by Django 4.1 on 2022-09-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdelete',
            old_name='admin',
            new_name='user',
        ),
    ]
