# Generated by Django 4.1 on 2022-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postdelete_delete_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
