# Generated by Django 4.1 on 2022-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_post_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.CharField(
                default="https://togedog.s3.ap-northeast-2.amazonaws.com/post_images/default_post_image.jpg",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="postdelete",
            name="delete_reason",
            field=models.CharField(blank=True, default="delete", max_length=200),
            preserve_default=False,
        ),
    ]
