# Generated by Django 4.1 on 2022-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_post_image_url_alter_postdelete_delete_reason"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("like_user_id", "post_id"), name="unique_post_like"
            ),
        ),
    ]
