# Generated by Django 4.1 on 2022-08-24 05:30

from django.db import migrations, models

import cores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("nickname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=600, null=True)),
                (
                    "social_account_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                (
                    "user_type",
                    cores.models.EnumField(
                        default=cores.models.UserType["NORMAL"],
                        enum=cores.models.UserType,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    cores.models.EnumField(
                        default=cores.models.UserStatus["ACTIVE"],
                        enum=cores.models.UserStatus,
                        max_length=10,
                    ),
                ),
                (
                    "account_type",
                    cores.models.EnumField(
                        enum=cores.models.UserAccountType, max_length=20
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(default="http://thumbnail.url", max_length=500),
                ),
                ("address", models.CharField(max_length=200, null=True)),
                ("mbti", models.CharField(default="none", max_length=4)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
