# Generated by Django 4.1 on 2022-09-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTestCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_count", models.PositiveIntegerField()),
            ],
        ),
    ]
