# Generated by Django 4.1 on 2022-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_status_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
    ]
