# Generated by Django 4.1 on 2022-09-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_address"),
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentDelete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delete_reason", models.CharField(blank=True, max_length=200)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_deletes",
                        to="users.user",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletes",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "db_table": "comment_delete",
            },
        ),
    ]
