# Generated by Django 4.1 on 2022-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_rename_admin_commentdelete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentReport",
        ),
    ]
