# Generated by Django 4.1 on 2022-09-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address'),
        ('comments', '0005_delete_commentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reported', to='users.user')),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reporter', to='users.user')),
            ],
            options={
                'db_table': 'comment_report',
            },
        ),
    ]
