# Generated by Django 4.1 on 2022-09-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_alter_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.CharField(max_length=30)),
                ("message_text", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=500)),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reported",
                        to="users.user",
                    ),
                ),
                (
                    "reporter_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reporter",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "chat_report",
            },
        ),
    ]
